### ISSUE TITLE
HMAC Issue

### ISSUE THREAD

**Issue by VincentChen1212** [hekeki/eckstein#1]
Hi, I Use Kotlin below
```
final String mtkKey = "key";
final String mtkAlgorithm = "HmacSHA256";

SecretKeySpec signingKey = new SecretKeySpec(mtkKey.getBytes("UTF-8"), mtkAlgorithm);

Mac mac = Mac.getInstance(mtkAlgorithm);
mac.init(signingKey);
byte[] bytes = mac.doFinal(data.getBytes("UTF-8"));


ret = base64Encode(bytes);
```

Use C# can get the same result

But Use this project 
I got different answer

I don't know which step I miss
```
HMAC.sha256(.......)
```

Thanks.

**Comment by VincentChen1212** [comment]
Hi, Update My Issue
I found HMAC is ok
But SHA256 has some error

When My Data length = 56
```
Data = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9eyJpc3MiOiJOZXh0IEN
Key = secret
```
The answer will Error

Thanks

**Comment by hekeki** [comment]
Hi 

HMAC.sha256("secret", "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9eyJpc3MiOiJOZXh0IEN");

I got:
9e961a147ba66aed57658e6a6fcf279491a21f592608dd1682f47bc605c4334e
which is the same result like here: https://www.freeformatter.com/hmac-generator.html#ad-output
It seems that Hmac sha256 is working correcly
